### ISSUE TITLE
Something wrong with the tar file of pretrained model

### ISSUE THREAD

**Issue by Azuresonance** [anhtuan85/Pytorch-SSD-from-scratch#1]
I downloaded it and cannot extract it.
```
$ tar -xf model_state_ssd300.pth.tar
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by Azuresonance** [comment]
Tried the whole process twice and couldn't make it work. Should be corrupted or something.

**Comment by anhtuan85** [comment]
No. You don't extract tar file. You can get link tar file when run. Example:
python detect.py --trained_model ./model_state_ssd300.pth.tar
